#*********************************************************************
#
#  PGPTools - PM shell for PGP v5.0 for OS/2
#
#  Module   : PGPTOOLS.EXP
#  Info     : Watcom C/C++ export definitions for PGPTOOLS.DLL
#  Author   : Bernd Giesen
#  Compiler : Watcom C/C++ v10.6
#
#  Copyright (c) 1999-2003 Bernd Giesen. All rights reserved.
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License as
#  published by the Free Software Foundation; either
#  version 2 of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#  General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston,
#  MA 02111-1307, USA.
#
#*********************************************************************
#
#  History:
#
#  130799 - Created
#
#*********************************************************************

PGPDLLInit.1=PGPDLLInit,
PGPDLLExit.2=PGPDLLExit,
PGPDLLSetGlobals.3=PGPDLLSetGlobals

